import { Course, Module } from '@/types';
import api from './axiosInstance';

export const courseApi = {
  getAll:      (params?: { search?: string; status?: string })  => api.get('/api/v1/courses', { params }),
  checkCode:   (code: string)  => api.get('/api/v1/courses/check-code', { params: { code } }),
  getOne:      (id: string)    => api.get(`/api/v1/courses/${id}`),
  create:      (data: Partial<Course>)     => api.post('/api/v1/courses', data),
  update:      (id: string, data: Partial<Course>)   => api.put(`/api/v1/courses/${id}`, data),
  delete:      (id: string)    => api.delete(`/api/v1/courses/${id}`),
  getStudents: (id: string)    => api.get(`/api/v1/courses/${id}/students`),
  enrollStudents: (id: string, studentIds: string[]) => api.post(`/api/v1/courses/${id}/students`, { studentIds }),
  enroll:      (id: string)    => api.post(`/api/v1/courses/${id}/enroll`),
  drop:        (id: string)    => api.delete(`/api/v1/courses/${id}/enroll`),
  getMyCourses: ()             => api.get('/api/v1/students/me/courses'),
  getModules:  (id: string)    => api.get(`/api/v1/courses/${id}/modules`),
  createModule:(id: string, data: Partial<Module>)   => api.post(`/api/v1/courses/${id}/modules`, data),
  createLesson:(id: string, modId: string, formData: FormData) => api.post(`/api/v1/courses/${id}/modules/${modId}/lessons`, formData, {
    headers: { 'Content-Type': 'multipart/form-data' },
  }),
  getAssignments: (id: string) => api.get(`/api/v1/courses/${id}/assignments`),
  createAssignment:(id: string, data: Record<string, unknown>)=> api.post(`/api/v1/courses/${id}/assignments`, data),
  getAssignment: (courseId: string, assignmentId: string) => api.get(`/api/v1/courses/${courseId}/assignments/${assignmentId}`),
  getMySubmission: (courseId: string, assignmentId: string) => api.get(`/api/v1/courses/${courseId}/assignments/${assignmentId}/my-submission`),
  getSubmissions: (courseId: string, assignmentId: string) => api.get(`/api/v1/courses/${courseId}/assignments/${assignmentId}/submissions`),
  submitAssignment: (courseId: string, assignmentId: string, data: FormData) => api.post(`/api/v1/courses/${courseId}/assignments/${assignmentId}/submit`, data, {
    headers: { 'Content-Type': 'multipart/form-data' }
  }),
  gradeSubmission: (courseId: string, submissionId: string, data: { grade: number; feedback: string }) => api.patch(`/api/v1/courses/${courseId}/submissions/${submissionId}/grade`, data),
  getQuizzes:  (id: string)    => api.get(`/api/v1/courses/${id}/quizzes`),
  createQuiz:  (id: string, data: Record<string, unknown>)   => api.post(`/api/v1/courses/${id}/quizzes`, data),
  getGradebook:(id: string)    => api.get(`/api/v1/courses/${id}/gradebook`),
  getAnalytics:(id: string)    => api.get(`/api/v1/courses/${id}/analytics`),
  getAtRisk:   (id: string)    => api.get(`/api/v1/courses/${id}/analytics/at-risk`),
  getGradeWeights:(id: string) => api.get(`/api/v1/courses/${id}/grade-weights`),
  setGradeWeights:(id: string, data: Record<string, number>) => api.post(`/api/v1/courses/${id}/grade-weights`, data),
  getAttendance:(id: string)   => api.get(`/api/v1/courses/${id}/attendance`),
  createAttendanceSession:(id: string, data: Record<string, unknown>)=> api.post(`/api/v1/courses/${id}/attendance`, data),
  markAttendance: (courseId: string, sessionId: string, records: { studentId: string; status: string }[]) => api.post(`/api/v1/courses/${courseId}/attendance/${sessionId}/mark`, { records }),
  getSessionRecords: (courseId: string, sessionId: string) => api.get(`/api/v1/courses/${courseId}/attendance/${sessionId}`),
  getStudentAttendance: (courseId: string) => api.get(`/api/v1/courses/${courseId}/my-attendance`),
  getAnnouncements:(id: string)=> api.get(`/api/v1/courses/${id}/announcements`),
  createAnnouncement:(id: string, data: { title: string; body: string })=>api.post(`/api/v1/courses/${id}/announcements`,data),
  getDiscussions:(id: string)  => api.get(`/api/v1/courses/${id}/discussions`),
  createDiscussion:(id: string, data: { title: string; body: string })=> api.post(`/api/v1/courses/${id}/discussions`, data),
  getLiveSessions:(id: string) => api.get(`/api/v1/courses/${id}/live-sessions`),
  createLiveSession:(id: string, data: Record<string, unknown>)=>api.post(`/api/v1/courses/${id}/live-sessions`,data),
  startLiveSession: (courseId: string, sessionId: string) => api.patch(`/api/v1/courses/${courseId}/live-sessions/${sessionId}/start`),
  endLiveSession: (courseId: string, sessionId: string) => api.patch(`/api/v1/courses/${courseId}/live-sessions/${sessionId}/end`),
  joinLiveSession: (courseId: string, sessionId: string) => api.get(`/api/v1/courses/${courseId}/live-sessions/${sessionId}/join`),
  getModuleContent: (courseId: string, modId: string) => api.get(`/api/v1/courses/${courseId}/modules/${modId}/content`),
  uploadContent: (courseId: string, modId: string, data: FormData) => api.post(`/api/v1/courses/${courseId}/modules/${modId}/lessons`, data, {
    headers: { 'Content-Type': 'multipart/form-data' }
  }),
  deleteContent: (contentId: string) => api.delete(`/api/v1/content/${contentId}`),
  getMySubmissions: (courseId: string) => api.get(`/api/v1/courses/${courseId}/my-submissions`),
  getStudentGrades: (courseId: string) => api.get(`/api/v1/students/me/grades/${courseId}`),
  getStudentFinalGrade: (courseId: string) => api.get(`/api/v1/students/me/grades/${courseId}/final`),
  getGlobalMilestones: () => api.get('/api/v1/students/me/milestones'),
};
